Name:           ros-indigo-rosjava-messages
Version:        0.2.2
Release:        1%{?dist}
Summary:        ROS rosjava_messages package

Group:          Development/Libraries
License:        Apache 2.0
URL:            http://ros.org/wiki/rosjava_messages
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-genjava
Requires:       ros-indigo-rosjava-build-tools
BuildRequires:  ros-indigo-actionlib-msgs
BuildRequires:  ros-indigo-ar-track-alvar-msgs
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-concert-msgs
BuildRequires:  ros-indigo-concert-service-msgs
BuildRequires:  ros-indigo-diagnostic-msgs
BuildRequires:  ros-indigo-gateway-msgs
BuildRequires:  ros-indigo-genjava
BuildRequires:  ros-indigo-geometry-msgs
BuildRequires:  ros-indigo-map-store
BuildRequires:  ros-indigo-move-base-msgs
BuildRequires:  ros-indigo-nav-msgs
BuildRequires:  ros-indigo-rocon-app-manager-msgs
BuildRequires:  ros-indigo-rocon-device-msgs
BuildRequires:  ros-indigo-rocon-interaction-msgs
BuildRequires:  ros-indigo-rocon-service-pair-msgs
BuildRequires:  ros-indigo-rocon-std-msgs
BuildRequires:  ros-indigo-rocon-tutorial-msgs
BuildRequires:  ros-indigo-roscpp
BuildRequires:  ros-indigo-rosgraph-msgs
BuildRequires:  ros-indigo-rosjava-build-tools
BuildRequires:  ros-indigo-rosjava-test-msgs
BuildRequires:  ros-indigo-scheduler-msgs
BuildRequires:  ros-indigo-sensor-msgs
BuildRequires:  ros-indigo-shape-msgs
BuildRequires:  ros-indigo-std-msgs
BuildRequires:  ros-indigo-std-srvs
BuildRequires:  ros-indigo-stereo-msgs
BuildRequires:  ros-indigo-tf2-msgs
BuildRequires:  ros-indigo-trajectory-msgs
BuildRequires:  ros-indigo-uuid-msgs
BuildRequires:  ros-indigo-visualization-msgs
BuildRequires:  ros-indigo-world-canvas-msgs
BuildRequires:  ros-indigo-yocs-msgs

%description
Message generation for rosjava.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Mon May 04 2015 Daniel Stonier <d.stonier@gmail.com> - 0.2.2-1
- Autogenerated by Bloom

* Wed Apr 22 2015 Daniel Stonier <d.stonier@gmail.com> - 0.2.2-0
- Autogenerated by Bloom

* Wed Feb 25 2015 Daniel Stonier <d.stonier@gmail.com> - 0.2.1-0
- Autogenerated by Bloom

